const S={apiUrl:localStorage.getItem('memoria_url')||'',pin:localStorage.getItem('memoria_pin')||'',cid:null,convs:[],allC:[],msgs:[],allMsgs:[],streaming:false,ac:null,models:[],provs:[],stk:[],selModel:localStorage.getItem('memoria_model')||'',attachments:[],curFolder:null,searchQ:'',searchResults:null,searchTimer:null,_hlMsgId:null};

// === IndexedDB 本地缓存层 ===
const IDB={db:null,NAME:'memoria_cache',VER:1};
function _idbOpen(){return new Promise((res,rej)=>{if(IDB.db)return res(IDB.db);const rq=indexedDB.open(IDB.NAME,IDB.VER);rq.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains('convs'))db.createObjectStore('convs',{keyPath:'id'});};rq.onsuccess=e=>{IDB.db=e.target.result;res(IDB.db);};rq.onerror=()=>rej(rq.error);});}
async function _idbGet(cid){try{const db=await _idbOpen();return new Promise((res,rej)=>{const tx=db.transaction('convs','readonly');const st=tx.objectStore('convs');const rq=st.get(cid);rq.onsuccess=()=>res(rq.result||null);rq.onerror=()=>res(null);});}catch(e){return null;}}
async function _idbPut(cid,allMsgs,msgs){try{const db=await _idbOpen();const _clone=typeof structuredClone==='function'?structuredClone:o=>JSON.parse(JSON.stringify(o));const data={id:cid,allMsgs:_clone(allMsgs||[]),msgs:_clone(msgs||[]),ts:Date.now()};return new Promise((res,rej)=>{const tx=db.transaction('convs','readwrite');const st=tx.objectStore('convs');st.put(data);tx.oncomplete=()=>{res(true);_idbTrim();};tx.onerror=()=>res(false);});}catch(e){return false;}}
async function _idbTrim(){try{const db=await _idbOpen();const tx=db.transaction('convs','readonly');const st=tx.objectStore('convs');const all=await new Promise(r=>{const rq=st.getAll();rq.onsuccess=()=>r(rq.result||[]);rq.onerror=()=>r([]);});if(all.length<=100)return;all.sort((a,b)=>b.ts-a.ts);const toDelete=all.slice(100);const tx2=db.transaction('convs','readwrite');const st2=tx2.objectStore('convs');toDelete.forEach(d=>st2.delete(d.id));}catch(e){}}
async function _idbDel(cid){try{const db=await _idbOpen();return new Promise((res)=>{const tx=db.transaction('convs','readwrite');tx.objectStore('convs').delete(cid);tx.oncomplete=()=>res(true);tx.onerror=()=>res(false);});}catch(e){return false;}}
function _cacheConv(){if(!S.cid)return;_idbPut(S.cid,S.allMsgs,S.msgs);}
// === 缓存层结束 ===
function _buildChildMap(all){const m=new Map();all.forEach(msg=>{const p=msg.parent_id||null;if(!m.has(p))m.set(p,[]);m.get(p).push(msg);});return m;}
function _rebuildActivePath(all){if(!all||!all.length)return[];const cm=_buildChildMap(all);const r=[];let pid=null;while(true){const ch=cm.get(pid)||[];if(!ch.length)break;let ac=ch.find(c=>c.is_active)||ch[0];ac.sibling_count=ch.length;if(ch.length>1)ac.siblings=ch.map(c=>({id:c.id,branch_index:c.branch_index}));r.push(ac);pid=ac.id;}return r;}
function _storeTree(d){if(d?.all_messages){S.allMsgs=d.all_messages;S.msgs=_rebuildActivePath(S.allMsgs);}else{S.msgs=d?.messages||[];S.allMsgs=[];}}
document.addEventListener('DOMContentLoaded',()=>{_initTheme();const inp=document.getElementById('msg-input');inp.value='';if(!S.apiUrl){openSet();goSP('conn');}else{Promise.all([loadConvs(),loadMdls()]);}aR(inp);updSub();/* #20 Service Worker registration */if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{});}});
function _initTheme(){const t=localStorage.getItem('memoria_theme')||'light';document.documentElement.setAttribute('data-theme',t);if(t==='dark')document.querySelector('meta[name="theme-color"]').content='#1A1A1A';const sw=document.getElementById('theme-sw');if(sw&&t==='dark')sw.classList.add('on');}
function toggleTheme(){const cur=document.documentElement.getAttribute('data-theme');const next=cur==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',next);localStorage.setItem('memoria_theme',next);document.querySelector('meta[name="theme-color"]').content=next==='dark'?'#1A1A1A':'#F5F5F0';const sw=document.getElementById('theme-sw');if(sw)sw.classList.toggle('on',next==='dark');document.querySelectorAll('.html-preview-frame').forEach(f=>{if(f.srcdoc){f.srcdoc='';f.style.height='200px';const wrap=f.closest('.html-preview-wrap');if(wrap)delete wrap.dataset.observed;}});_initHtmlPreviews();}

const SB_ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZWFlbXhydWxrY2Frd3B1dWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMTkwOTksImV4cCI6MjA4Nzc5NTA5OX0.1hkMSX8weGk6t55BbcKFTkjJN72APl4JNvqdfWedpw0';
async function api(a,p={},s=false){if(!S.apiUrl)return null;const h={'Content-Type':'application/json','Authorization':'Bearer '+SB_ANON};if(S.pin)h['x-app-pin']=S.pin;const b=JSON.stringify({action:a,...p});if(s){S.ac=new AbortController();const _t=setTimeout(()=>S.ac.abort(),60000);const r=await fetch(S.apiUrl,{method:'POST',headers:h,body:b,signal:S.ac.signal});clearTimeout(_t);if(!r.ok)throw new Error(r.status);return r;}const _ac=new AbortController();const _t=setTimeout(()=>_ac.abort(),30000);const r=await fetch(S.apiUrl,{method:'POST',headers:h,body:b,signal:_ac.signal});clearTimeout(_t);if(!r.ok)throw new Error(r.status);return r.json();}
function E(s){return s?s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'):'';}
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2e3);}
function cMo(){document.getElementById('cf-mo').classList.remove('on');}
function confirm_(t,tx,fn){document.getElementById('cf-t').textContent=t;document.getElementById('cf-tx').textContent=tx;document.getElementById('cf-ok').onclick=()=>{cMo();fn();};document.getElementById('cf-mo').classList.add('on');}
function tgEl(id){const e=document.getElementById(id);e.style.display=e.style.display==='none'?'block':'none';if(id==='m-form'&&e.style.display!=='none'){const sel=document.getElementById('m-prov');sel.innerHTML=S.provs.map(p=>'<option value="'+p.id+'">'+E(p.name)+'</option>').join('');}}
function hEl(id){document.getElementById(id).style.display='none';}
function scr(force){const c=document.getElementById('msgs-wrap');const atBottom=c.scrollHeight-c.scrollTop-c.clientHeight<150;if(force||atBottom)requestAnimationFrame(()=>c.scrollTop=c.scrollHeight);}
function aR(e){if(!e)return;e.style.height='auto';e.style.height=Math.min(e.scrollHeight,140)+'px';}
function hIK(e){if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();send();}}
function gMdl(){return S.selModel||S.models.find(m=>m.is_default)?.model_id||'anthropic/claude-sonnet-4';}
function updSub(){const mid=gMdl(),m=S.models.find(x=>x.model_id===mid);const tbm=document.getElementById('tb-model');if(tbm)tbm.textContent=m?.display_name||mid.split('/').pop()||'选择模型';}
function updSendBtn(){const b=document.getElementById('send-btn'),v=document.getElementById('msg-input').value.trim()||S.attachments.length>0;b.classList.toggle('ready',!!v);}
document.getElementById('msg-input').addEventListener('input',function(){updSendBtn();});

// File attachments
function onImgPick(inp){const files=Array.from(inp.files);inp.value='';for(const f of files){if(f.size>10*1024*1024){toast('图片不能超过 10MB');continue;}const item={file:f,type:'image',name:f.name,size:f.size};const rd=new FileReader();rd.onload=e=>{item.preview=e.target.result;S.attachments.push(item);rAttach();};rd.readAsDataURL(f);}}
async function onFilePick(inp){const f=inp.files[0];if(!f)return;inp.value='';if(f.size>20*1024*1024){toast('文件不能超过 20MB');return;}toast('正在读取文档...');try{const text=await extractFileText(f);if(!text){toast('不支持此格式或提取失败');return;}const item={type:'document',name:f.name,size:f.size,text:text.substring(0,30000)};S.attachments.push(item);rAttach();toast(f.name+' 已添加');}catch(e){toast('文件读取失败');}}
function rAttach(){const el=document.getElementById('attach-preview');if(!S.attachments.length){el.classList.remove('on');el.innerHTML='';updSendBtn();return;}el.classList.add('on');el.innerHTML=S.attachments.map((a,i)=>{const icon=a.type==='image'&&a.preview?'<img src="'+a.preview+'">':'<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--t3)" stroke-width="1.8"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/></svg>';const sz=a.type==='document'&&a.text?(a.text.length>1000?Math.round(a.text.length/1000)+'k字符':a.text.length+'字符'):a.size<1024?a.size+'B':a.size<1024*1024?(a.size/1024).toFixed(0)+'KB':(a.size/1024/1024).toFixed(1)+'MB';return '<div class="att-item">'+icon+'<span class="att-name">'+E(a.name)+' <span style="color:var(--t4)">'+sz+'</span></span><button class="att-rm" onclick="rmAttach('+i+')"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 6L6 18M6 6l12 12"/></svg></button></div>';}).join('');updSendBtn();}
function rmAttach(i){S.attachments.splice(i,1);rAttach();}

// Image compression
function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=async e=>{const MAX=1200;try{/* Fast path: createImageBitmap is non-blocking */if(typeof createImageBitmap==='function'){const blob=new Blob([e.target.result]);const bmp=await createImageBitmap(blob);let w=bmp.width,h=bmp.height;if(w>MAX||h>MAX){if(w>h){h=Math.round(h*MAX/w);w=MAX;}else{w=Math.round(w*MAX/h);h=MAX;}}/* Prefer OffscreenCanvas to avoid main-thread layout */if(typeof OffscreenCanvas!=='undefined'){const oc=new OffscreenCanvas(w,h);const ctx=oc.getContext('2d');ctx.drawImage(bmp,0,0,w,h);bmp.close();const oBlob=await oc.convertToBlob({type:'image/jpeg',quality:0.7});const r2=new FileReader();r2.onload=()=>resolve(r2.result);r2.onerror=reject;r2.readAsDataURL(oBlob);return;}/* Fallback to regular canvas */const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(bmp,0,0,w,h);bmp.close();resolve(canvas.toDataURL('image/jpeg',0.7));return;}}catch(ex){/* fall through to legacy */}/* Legacy path */const img=new Image();img.onload=()=>{let w=img.width,h=img.height;if(w>MAX||h>MAX){if(w>h){h=Math.round(h*MAX/w);w=MAX;}else{w=Math.round(w*MAX/h);h=MAX;}}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',0.7));};img.onerror=reject;img.src=e.target.result;};reader.onerror=reject;reader.readAsDataURL(file);});}
function viewImg(url){const d=document.createElement('div');d.className='msg-img-full';d.onclick=()=>d.remove();d.innerHTML='<img src="'+url+'">';document.body.appendChild(d);}

// Document text extraction
function loadLib(url){return new Promise((res,rej)=>{if(document.querySelector('script[src="'+url+'"]')){res();return;}const s=document.createElement('script');s.src=url;s.onload=res;s.onerror=rej;document.head.appendChild(s);})}
async function extractFileText(file){const ext=file.name.split('.').pop().toLowerCase();if(['txt','md','csv','json'].includes(ext))return await file.text();if(ext==='pdf'){try{await loadLib('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const ab=await file.arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;let t='';for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i);const tc=await pg.getTextContent();t+=tc.items.map(x=>x.str).join(' ')+'\n';}return t;}catch(e){return null;}}if(['doc','docx'].includes(ext)){try{await loadLib('https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.8.0/mammoth.browser.min.js');const ab=await file.arrayBuffer();const r=await mammoth.extractRawText({arrayBuffer:ab});return r.value;}catch(e){return null;}}if(ext==='xlsx'){try{await loadLib('https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js');const ab=await file.arrayBuffer();const wb=XLSX.read(ab,{type:'array'});let t='';for(const sn of wb.SheetNames){t+='['+sn+']\n'+XLSX.utils.sheet_to_csv(wb.Sheets[sn])+'\n\n';}return t;}catch(e){return null;}}return null;}

// Settings nav
function openSet(){document.getElementById('settings').classList.add('on');S.stk=['home'];document.querySelectorAll('.sp').forEach(p=>p.classList.remove('on','out'));document.getElementById('sp-home').classList.add('on');}
function openQuickSP(pg){document.getElementById('settings').classList.add('on');S.stk=[pg];document.querySelectorAll('.sp').forEach(p=>p.classList.remove('on','out'));document.getElementById('sp-'+pg).classList.add('on');if(pg==='models'){loadProvs();loadMdlSet();}if(pg==='notes')loadNotes();if(pg==='avatar')loadAvatarSettings();}
function closeSet(){const el=document.getElementById('settings');el.classList.remove('on');S.stk=[];}
function goSP(pg){if(!document.getElementById('settings').classList.contains('on'))openSet();const cur=S.stk[S.stk.length-1];if(cur){const ce=document.getElementById('sp-'+cur);if(ce){ce.classList.add('out');ce.classList.remove('on');}}S.stk.push(pg);const el=document.getElementById('sp-'+pg);if(el){el.classList.remove('out');el.classList.add('on');}if(pg==='prov')loadProvs();if(pg==='models'){loadProvs();loadMdlSet();}if(pg==='mcp')loadMCPs();if(pg==='notes')loadNotes();if(pg==='core')loadCore();if(pg==='conn'){document.getElementById('s-url').value=S.apiUrl;document.getElementById('s-pin').value=S.pin;}if(pg==='data')loadData();if(pg==='chatparams')loadChatParams();}
function backSP(){if(S.stk.length<=1){closeSet();return;}const cur=S.stk.pop();document.getElementById('sp-'+cur).classList.remove('on');const prev=S.stk[S.stk.length-1];document.getElementById('sp-'+prev).classList.remove('out');document.getElementById('sp-'+prev).classList.add('on');}

