const PRESETS={deepseek:{name:'DeepSeek',base_url:'https://api.deepseek.com/v1',color:'#4D6BFE',abbr:'DS',desc:'api.deepseek.com · 便宜好用',models:[{id:'deepseek-chat',name:'DeepSeek V3',util:true},{id:'deepseek-reasoner',name:'DeepSeek R1',util:false}]},openrouter:{name:'OpenRouter',base_url:'https://openrouter.ai/api/v1',color:'#6B5CE7',abbr:'OR',desc:'openrouter.ai · 多模型聚合',models:[{id:'anthropic/claude-sonnet-4',name:'Claude Sonnet 4',util:false},{id:'anthropic/claude-haiku-4',name:'Claude Haiku 4',util:true},{id:'google/gemini-2.5-flash',name:'Gemini 2.5 Flash',util:true},{id:'google/gemini-2.5-pro',name:'Gemini 2.5 Pro',util:false},{id:'deepseek/deepseek-chat-v3-0324',name:'DeepSeek V3 (OR)',util:true},{id:'deepseek/deepseek-r1',name:'DeepSeek R1 (OR)',util:false},{id:'openai/gpt-4.1-mini',name:'GPT-4.1 Mini',util:true},{id:'openai/gpt-4.1',name:'GPT-4.1',util:false}]},openai:{name:'OpenAI',base_url:'https://api.openai.com/v1',color:'#10A37F',abbr:'AI',desc:'api.openai.com · GPT 系列',models:[{id:'gpt-4.1-mini',name:'GPT-4.1 Mini',util:true},{id:'gpt-4.1',name:'GPT-4.1',util:false},{id:'gpt-4o',name:'GPT-4o',util:false},{id:'o4-mini',name:'o4-mini',util:false}]},siliconflow:{name:'SiliconFlow',base_url:'https://api.siliconflow.cn/v1',color:'#6366F1',abbr:'SF',desc:'siliconflow.cn · 国产聚合',models:[{id:'deepseek-ai/DeepSeek-V3',name:'DeepSeek V3',util:true},{id:'deepseek-ai/DeepSeek-R1',name:'DeepSeek R1',util:false},{id:'Qwen/Qwen3-235B-A22B',name:'Qwen3 235B',util:false},{id:'Qwen/Qwen3-30B-A3B',name:'Qwen3 30B',util:true}]},gemini:{name:'Gemini',base_url:'https://generativelanguage.googleapis.com/v1beta/openai',color:'#4285F4',abbr:'G',desc:'Google AI Studio · Gemini',models:[{id:'gemini-2.5-flash',name:'Gemini 2.5 Flash',util:true},{id:'gemini-2.5-pro',name:'Gemini 2.5 Pro',util:false}]},qwen:{name:'阿里云千问',base_url:'https://dashscope.aliyuncs.com/compatible-mode/v1',color:'#FF6A00',abbr:'千问',desc:'dashscope.aliyuncs.com · 通义千问',models:[{id:'qwen-plus',name:'Qwen Plus',util:true},{id:'qwen-max',name:'Qwen Max',util:false},{id:'qwen-turbo',name:'Qwen Turbo',util:true}]},zhipu:{name:'智谱',base_url:'https://open.bigmodel.cn/api/paas/v4',color:'#2563EB',abbr:'智谱',desc:'bigmodel.cn · GLM 系列',models:[{id:'glm-4-plus',name:'GLM-4 Plus',util:false},{id:'glm-4-flash',name:'GLM-4 Flash',util:true}]}};

// Providers
async function loadProvs(){try{const d=await api('list_providers');S.provs=d?.providers||[];rProvs();rProvPresets();}catch(e){}}
function rProvs(){const el=document.getElementById('p-list');if(!el)return;if(!S.provs.length){el.innerHTML='<div class="sp-empty">暂无供应商，请从下方添加</div>';return;}el.innerHTML='<div class="sl">'+S.provs.map(p=>{const pk=Object.keys(PRESETS).find(k=>PRESETS[k].name===p.name);const pr=pk?PRESETS[pk]:null;const bg=pr?.color||'#8C8478';const ab=pr?.abbr||p.name.substring(0,2);return '<div class="prov-item" onclick="openProvDetail(\''+p.id+'\')"><div class="prov-icon" style="background:'+bg+'">'+ab+'</div><div class="prov-info"><div class="prov-name">'+E(p.name)+'</div></div><span class="badge b-green">启用</span><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--t4)" stroke-width="2"><path d="M9 18l6-6-6-6"/></svg></div>';}).join('')+'</div>';}
function rProvPresets(){const el=document.getElementById('p-presets');if(!el)return;const existing=new Set(S.provs.map(p=>p.name));el.innerHTML=Object.keys(PRESETS).map(k=>{const p=PRESETS[k];const added=existing.has(p.name);return '<div class="prov-item'+(added?' ':'')+'" onclick="'+(added?'':'addPreset(\''+k+'\')')+'"><div class="prov-icon" style="background:'+(added?'var(--bg3)':p.color)+'">'+p.abbr+'</div><div class="prov-info"><div class="prov-name">'+E(p.name)+(added?' <span class="badge b-green">已添加</span>':'')+'</div><div style="font-size:12px;color:var(--t3)">'+E(p.desc)+'</div></div>'+(added?'':'<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--t4)" stroke-width="2"><path d="M9 18l6-6-6-6"/></svg>')+'</div>';}).join('')+'<div class="prov-item" onclick="addPreset(\'custom\')"><div class="prov-icon" style="background:var(--t3)">+</div><div class="prov-info"><div class="prov-name">自定义</div><div style="font-size:12px;color:var(--t3)">手动填写 Base URL</div></div><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--t4)" stroke-width="2"><path d="M9 18l6-6-6-6"/></svg></div>';}
function addPreset(key){S._preset=key;if(key==='custom'){document.getElementById('pa-title').textContent='自定义供应商';document.getElementById('pa-label').textContent='API Key';document.getElementById('pa-custom').style.display='block';}else{const p=PRESETS[key];document.getElementById('pa-title').textContent='添加 '+p.name;document.getElementById('pa-label').textContent=p.name+' API Key';document.getElementById('pa-custom').style.display='none';}document.getElementById('pa-key').value='';goSP('prov-add');}
async function saveNewProv(){const k=document.getElementById('pa-key').value.trim();if(!k){toast('请输入 API Key');return;}let n,u;if(S._preset&&S._preset!=='custom'){const p=PRESETS[S._preset];n=p.name;u=p.base_url;}else{n=document.getElementById('pa-name').value.trim();u=document.getElementById('pa-url').value.trim();if(!n||!u){toast('请填写完整');return;}}try{const res=await api('create_provider',{name:n,base_url:u,api_key:k});await loadProvs();const pid=res?.provider?.id;if(pid){S._editProv=pid;backSP();openProvDetail(pid);setTimeout(()=>pdTab('mdls'),100);}toast('已添加');S._preset=null;}catch(e){toast('失败');}}
function openProvDetail(pid){const p=S.provs.find(x=>x.id===pid);if(!p)return;S._editProv=pid;S._editProvData=p;document.getElementById('pd-title').textContent=p.name;document.getElementById('pd-name').value=p.name;document.getElementById('pd-key').value='';document.getElementById('pd-key').placeholder='••••••••（留空不修改）';document.getElementById('pd-url').value=p.base_url;document.getElementById('pd-enabled').checked=true;document.getElementById('pd-test-result').innerHTML='';hEl('pd-mdl-form');goSP('prov-detail');pdTab('cfg');loadProvModels();}
function pdTab(t){document.getElementById('pd-cfg').style.display=t==='cfg'?'block':'none';document.getElementById('pd-mdls').style.display=t==='mdls'?'block':'none';document.getElementById('pd-tab-cfg').classList.toggle('on',t==='cfg');document.getElementById('pd-tab-mdls').classList.toggle('on',t==='mdls');}
function togglePdKey(){const i=document.getElementById('pd-key');i.type=i.type==='password'?'text':'password';}
async function saveProvDetail(){const pid=S._editProv;if(!pid)return;const upd={provider_id:pid};const n=document.getElementById('pd-name').value.trim();const u=document.getElementById('pd-url').value.trim();const k=document.getElementById('pd-key').value.trim();if(n)upd.name=n;if(u)upd.base_url=u;if(k)upd.api_key=k;try{await api('update_provider',upd);await loadProvs();document.getElementById('pd-title').textContent=n||S._editProvData?.name;toast('已保存');}catch(e){toast('失败');}}
function delProvDetail(){confirm_('删除供应商','关联的模型也会不可用',async()=>{try{await api('delete_provider',{provider_id:S._editProv});await Promise.all([loadProvs(),loadMdls()]);backSP();toast('已删除');}catch(e){toast('失败');}});}
async function testProvConn(){const pid=S._editProv;const p=S.provs.find(x=>x.id===pid);if(!p)return;const el=document.getElementById('pd-test-result');el.innerHTML='<span class="pd-status testing">测试中...</span>';try{const headers={'Content-Type':'application/json'};if(S.pin)headers['x-app-pin']=S.pin;const r=await fetch(S.apiUrl,{method:'POST',headers,body:JSON.stringify({action:'test_provider',provider_id:pid})});if(r.ok){const d=await r.json();if(d.success)el.innerHTML='<span class="pd-status ok">✓ 连接成功</span>';else el.innerHTML='<span class="pd-status err">✗ '+E(d.error||'连接失败')+'</span>';}else{el.innerHTML='<span class="pd-status ok">✓ 已保存（可直接使用）</span>';}}catch(e){el.innerHTML='<span class="pd-status ok">✓ 已保存（可直接使用）</span>';}}
function loadProvModels(){const pid=S._editProv;const provModels=S.models.filter(m=>m.provider_id===pid);rProvModels(provModels);showPresetModels();}
function rProvModels(ms){const el=document.getElementById('pd-model-list');if(!ms.length){el.innerHTML='<div class="sp-empty">暂无模型，点击下方获取或手动添加</div>';return;}el.innerHTML='<div class="sl">'+ms.map(m=>'<div class="si"><div class="si-info"><div class="si-n">'+E(m.display_name)+(m.is_default?' <span class="badge b-blue">默认</span>':'')+(m.is_utility?' <span class="badge b-orange">工具</span>':'')+(S.selModel===m.model_id?' <span class="badge b-green">当前</span>':'')+'</div><div class="si-d">'+E(m.model_id)+'</div></div><div class="si-acts"><button class="si-btn del" onclick="delProvMdl(\''+m.id+'\')">删除</button></div></div>').join('')+'</div>';}
function showPresetModels(){const pid=S._editProv;const p=S.provs.find(x=>x.id===pid);if(!p)return;const pk=Object.keys(PRESETS).find(k=>PRESETS[k].name===p.name);if(!pk){document.getElementById('pd-preset-models').style.display='none';return;}const preset=PRESETS[pk];const existing=new Set(S.models.map(m=>m.model_id));document.getElementById('pd-preset-label').textContent='推荐模型';document.getElementById('pd-preset-list').innerHTML=preset.models.map(m=>{const added=existing.has(m.id);return '<div class="sr" style="'+(added?'opacity:.5':'')+'" onclick="'+(added?'':'quickAddMdl(\''+E(m.id)+'\',\''+E(m.name)+'\','+(m.util?'true':'false')+')')+'"><div class="sr-body"><div class="sr-title">'+E(m.name)+(m.util?' <span class="badge b-orange">工具</span>':'')+(added?' <span class="badge b-green">已添加</span>':'')+'</div><div class="sr-desc">'+E(m.id)+'</div></div>'+(added?'':'<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg>')+'</div>';}).join('');document.getElementById('pd-preset-models').style.display='block';}
async function quickAddMdl(mid,name,util){const pid=S._editProv;try{await api('create_model',{provider_id:pid,model_id:mid,display_name:name,is_default:S.models.length===0,is_utility:util});await loadMdls(true);loadProvModels();if(S._fetchedModels)filterFetchedModels();toast(name+' 已添加');}catch(e){toast('失败');}}
function showAddMdlForm(){const f=document.getElementById('pd-mdl-form');f.style.display=f.style.display==='none'?'block':'none';document.getElementById('pd-mid').value='';document.getElementById('pd-mname').value='';}
async function saveProvMdl(){const mid=document.getElementById('pd-mid').value.trim(),nm=document.getElementById('pd-mname').value.trim();if(!mid||!nm){toast('请填写完整');return;}try{await api('create_model',{provider_id:S._editProv,model_id:mid,display_name:nm,is_default:document.getElementById('pd-mdef').checked,is_utility:document.getElementById('pd-mutil').checked});hEl('pd-mdl-form');await loadMdls(true);loadProvModels();toast('已添加');}catch(e){toast('失败');}}
async function delProvMdl(id){try{await api('delete_model',{id});await loadMdls(true);loadProvModels();toast('已删除');}catch(e){toast('失败');}}
async function fetchProvModels(){toast('正在获取...');const pid=S._editProv;const p=S.provs.find(x=>x.id===pid);if(!p){toast('供应商不存在');return;}try{const h={'Content-Type':'application/json'};if(S.pin)h['x-app-pin']=S.pin;const r=await fetch(S.apiUrl,{method:'POST',headers:h,body:JSON.stringify({action:'fetch_models',provider_id:pid})});if(!r.ok)throw new Error(r.status);const d=await r.json();if(d.models&&d.models.length>0){toast('获取到 '+d.models.length+' 个模型');showFetchedModels(d.models);}else{toast('未获取到模型，请手动添加');}}catch(e){toast('获取失败，请手动添加');}}
function showFetchedModels(models){const existing=new Set(S.models.map(m=>m.model_id));S._fetchedModels=models;document.getElementById('pd-preset-label').textContent='从 API 获取的模型 ('+models.length+')';document.getElementById('pd-fetch-search').style.display=models.length>10?'block':'none';document.getElementById('pd-fetch-q').value='';renderFetchedModels(models,existing);document.getElementById('pd-preset-models').style.display='block';}
function filterFetchedModels(){const q=(document.getElementById('pd-fetch-q').value||'').toLowerCase().trim();const existing=new Set(S.models.map(m=>m.model_id));if(!q){renderFetchedModels(S._fetchedModels||[],existing);return;}const filtered=(S._fetchedModels||[]).filter(m=>{const mid=(m.id||m.model_id||'').toLowerCase();const name=(m.name||'').toLowerCase();return mid.includes(q)||name.includes(q);});renderFetchedModels(filtered,existing);}
function renderFetchedModels(models,existing){const groups={};models.forEach(m=>{const mid=m.id||m.model_id||'';const parts=mid.split('/');const vendor=parts.length>1?parts[0]:'其他';if(!groups[vendor])groups[vendor]=[];groups[vendor].push(m);});const vendorNames={'anthropic':'Anthropic','google':'Google','openai':'OpenAI','deepseek':'DeepSeek','meta-llama':'Meta Llama','mistralai':'Mistral','qwen':'Qwen','cohere':'Cohere','microsoft':'Microsoft','x-ai':'xAI','nvidia':'NVIDIA','perplexity':'Perplexity','amazon':'Amazon','nousresearch':'Nous Research'};let html='';const sortedVendors=Object.keys(groups).sort((a,b)=>{const pa=['anthropic','google','openai','deepseek','meta-llama','mistralai','qwen'];const ia=pa.indexOf(a),ib=pa.indexOf(b);if(ia>=0&&ib>=0)return ia-ib;if(ia>=0)return -1;if(ib>=0)return 1;return a.localeCompare(b);});for(const vendor of sortedVendors){const vModels=groups[vendor];const vName=vendorNames[vendor]||vendor;html+='<div style="padding:8px 16px 4px;font-size:11px;font-weight:600;color:var(--t3);text-transform:uppercase;letter-spacing:.5px">'+E(vName)+' ('+vModels.length+')</div>';html+=vModels.map(m=>{const mid=m.id||m.model_id||'';const name=m.name||mid;const added=existing.has(mid);return '<div class="sr" style="'+(added?'opacity:.5':'')+'" onclick="'+(added?'':'quickAddMdl(\''+E(mid)+'\',\''+E(name)+'\',false)')+'"><div class="sr-body"><div class="sr-title">'+E(name)+(added?' <span class="badge b-green">已添加</span>':'')+'</div><div class="sr-desc">'+E(mid)+'</div></div>'+(added?'':'<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg>')+'</div>';}).join('');}document.getElementById('pd-preset-list').innerHTML=html||'<div class="sp-empty">无匹配模型</div>';}

// Models
async function loadMdls(alsoSet){try{const d=await api('list_models');S.models=d?.models||[];updSub();if(alsoSet)rMdlSet();}catch(e){}}
async function loadMdlSet(){return loadMdls(true);}
function rMdlSet(){const el=document.getElementById('m-list');if(!el)return;if(!S.models.length){el.innerHTML='<div class="sp-empty">暂无模型，请先添加供应商</div>';return;}el.innerHTML='<div class="sc">'+S.models.map(m=>'<div class="si" onclick="selMdl(\''+E(m.model_id)+'\')" style="cursor:pointer"><div class="si-info"><div class="si-n">'+E(m.display_name)+(m.is_default?' <span class="badge b-blue">默认</span>':'')+(m.is_utility?' <span class="badge b-orange">工具</span>':'')+(S.selModel===m.model_id?' <span class="badge b-green">当前</span>':'')+'</div><div class="si-d">'+E(m.model_id)+(m.providers?' · '+E(m.providers.name):'')+'</div></div></div>').join('')+'</div>';}
function selMdl(mid){S.selModel=mid;localStorage.setItem('memoria_model',mid);updSub();closeSet();toast('已切换');}
async function delMdl(id){try{await api('delete_model',{id});loadMdls(true);toast('已删除');}catch(e){toast('失败');}}

// MCP
async function loadMCPs(){try{const d=await api('list_mcp_servers');rMCPs(d?.servers||[]);}catch(e){}}
function rMCPs(svs){const el=document.getElementById('mcp-list');if(!el)return;if(!svs.length){el.innerHTML='<div class="sp-empty">暂无 MCP Server</div>';return;}el.innerHTML='<div class="sc">'+svs.map(s=>'<div class="si"><div class="si-info"><div class="si-n">'+E(s.name)+' <span style="font-size:12px;color:var(--t4)">'+(s.tool_count||0)+' tools</span></div><div class="si-d">'+E(s.sse_url)+'</div></div><div class="si-acts"><label class="tgl"><input type="checkbox" '+(s.enabled?'checked':'')+' onchange="tgMCP(\''+s.id+'\',this.checked)"><span></span></label><button class="si-btn" onclick="syncMCP(\''+s.id+'\')">同步</button><button class="si-btn del" onclick="delMCP(\''+s.id+'\')">删除</button></div></div>').join('')+'</div>';}
async function saveMCP(){const n=document.getElementById('mcp-n').value.trim(),u=document.getElementById('mcp-u').value.trim(),a=document.getElementById('mcp-a').value.trim();if(!n||!u){toast('请填写');return;}try{await api('create_mcp_server',{name:n,sse_url:u,auth_header:a||undefined});hEl('mcp-form');loadMCPs();toast('已添加');}catch(e){toast('失败');}}
async function tgMCP(id,en){try{await api('update_mcp_server',{server_id:id,enabled:en});}catch(e){toast('失败');}}
async function syncMCP(id){try{const d=await api('sync_mcp_tools',{server_id:id});toast('同步 '+d.synced+' 个工具');loadMCPs();}catch(e){toast('同步失败');}}
async function delMCP(id){try{await api('delete_mcp_server',{server_id:id});loadMCPs();toast('已删除');}catch(e){toast('失败');}}

// Notes
async function loadNotes(){try{const d=await api('list_notes');rNotes(d?.notes||[]);}catch(e){}}
function rNotes(ns){const el=document.getElementById('n-list');if(!el)return;if(!ns.length){el.innerHTML='<div class="sp-empty">暂无便签</div>';return;}el.innerHTML=ns.map(n=>{const t=n.updated_at?fmtMsgTime(n.updated_at):(n.created_at?fmtMsgTime(n.created_at):'');const preview=n.content.length>40?n.content.substring(0,40)+'…':n.content;return '<div class="nc'+(n.pinned?' pin':'')+'" id="nc-'+n.id+'"><div class="nc-header" onclick="tgNoteCollapse(this)"><svg class="nc-arrow" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 18l6-6-6-6"/></svg><span class="nc-preview">'+E(preview)+'</span>'+(n.pinned?'<span style="font-size:11px;color:var(--accent)">置顶</span>':'')+'</div><div class="nc-detail"><div class="nc-body" id="ncb-'+n.id+'">'+E(n.content)+'</div>'+(t?'<div class="nc-time">最后编辑 '+t+'</div>':'')+'<div class="nc-acts"><button class="nc-btn" onclick="edNote(\''+n.id+'\')">编辑</button><button class="nc-btn" onclick="edNoteFS(\''+n.id+'\')">全屏编辑</button><button class="nc-btn" onclick="tgPin(\''+n.id+'\','+!n.pinned+')">'+(n.pinned?'取消置顶':'置顶')+'</button><button class="nc-btn" onclick="delNote(\''+n.id+'\')">删除</button></div></div></div>';}).join('');}
function tgNoteCollapse(hdr){hdr.classList.toggle('open');}
function edNote(id){const el=document.getElementById('ncb-'+id);if(!el)return;const cur=el.textContent;el.innerHTML='<textarea class="ed-ta" style="min-height:80px">'+E(cur)+'</textarea><div class="ed-btns"><button class="btn btn-g btn-s" onclick="loadNotes()">取消</button><button class="btn btn-p btn-s" onclick="svNote(\''+id+'\')">保存</button></div>';el.querySelector('textarea').focus();}
function edNoteFS(id){const el=document.getElementById('ncb-'+id);if(!el)return;const cur=el.textContent;const ov=document.createElement('div');ov.className='note-fs-overlay';ov.id='note-fs-ov';ov.innerHTML='<div class="note-fs-hd"><button class="nfs-cancel" onclick="closeNoteFS()">取消</button><button onclick="svNoteFS(\''+id+'\')">保存</button></div><textarea class="note-fs-ta" id="note-fs-ta">'+cur.replace(/&/g,'&amp;').replace(/</g,'&lt;')+'</textarea>';document.body.appendChild(ov);ov.querySelector('textarea').focus();}
function closeNoteFS(){const ov=document.getElementById('note-fs-ov');if(ov)ov.remove();}
async function svNoteFS(id){const ta=document.getElementById('note-fs-ta');if(!ta)return;const c=ta.value.trim();if(!c)return;try{await api('update_note',{note_id:id,content:c});closeNoteFS();loadNotes();toast('已保存');}catch(e){toast('失败');}}
async function svNote(id){const ta=document.querySelector('#ncb-'+id+' textarea');if(!ta)return;const c=ta.value.trim();if(!c)return;try{await api('update_note',{note_id:id,content:c});loadNotes();toast('已保存');}catch(e){toast('失败');}}
async function addNote(){const c=document.getElementById('n-in').value.trim();if(!c)return;try{await api('create_note',{content:c});document.getElementById('n-in').value='';loadNotes();toast('已添加');}catch(e){toast('失败');}}
async function tgPin(id,p){try{await api('update_note',{note_id:id,pinned:p});loadNotes();}catch(e){toast('失败');}}
async function delNote(id){try{await api('delete_note',{note_id:id});loadNotes();toast('已删除');}catch(e){toast('失败');}}

// Avatar settings
function loadAvatarSettings(){const d=JSON.parse(localStorage.getItem('memoria_avatar')||'{}');document.getElementById('av-name').value=d.name||'';if(d.img){document.getElementById('av-preview').src=d.img;document.getElementById('av-preview').style.display='block';document.getElementById('av-placeholder').style.display='none';document.getElementById('av-clear-btn').style.display='inline';}else{document.getElementById('av-preview').style.display='none';document.getElementById('av-placeholder').style.display='block';document.getElementById('av-clear-btn').style.display='none';}}
function onAvatarFile(inp){const f=inp.files[0];if(!f)return;const reader=new FileReader();reader.onload=e=>{const img=new Image();img.onload=()=>{const sz=128;const c=document.createElement('canvas');c.width=sz;c.height=sz;const ctx=c.getContext('2d');const s=Math.min(img.width,img.height);const sx=(img.width-s)/2,sy=(img.height-s)/2;ctx.drawImage(img,sx,sy,s,s,0,0,sz,sz);const b64=c.toDataURL('image/jpeg',0.8);document.getElementById('av-preview').src=b64;document.getElementById('av-preview').style.display='block';document.getElementById('av-placeholder').style.display='none';document.getElementById('av-clear-btn').style.display='inline';};img.src=e.target.result;};reader.readAsDataURL(f);}
function clearAvatar(){document.getElementById('av-preview').style.display='none';document.getElementById('av-preview').src='';document.getElementById('av-placeholder').style.display='block';document.getElementById('av-clear-btn').style.display='none';document.getElementById('av-file').value='';}
function clearAvatarAll(){clearAvatar();document.getElementById('av-name').value='';localStorage.removeItem('memoria_avatar');toast('已恢复默认');rMsgs();}
function saveAvatar(){const d={};const n=document.getElementById('av-name').value.trim();if(n)d.name=n;const img=document.getElementById('av-preview');if(img.style.display!=='none'&&img.src)d.img=img.src;if(Object.keys(d).length)localStorage.setItem('memoria_avatar',JSON.stringify(d));else localStorage.removeItem('memoria_avatar');toast('已保存');rMsgs();}
function getCustomAvatar(){try{return JSON.parse(localStorage.getItem('memoria_avatar')||'{}');}catch(e){return {};}}

// Core identity
async function loadCore(){try{const d=await api('get_system_config',{key:'cross_window_memory'});const v=d?.value||'';document.getElementById('core-ta').value=v;document.getElementById('core-len').textContent=v.length+' 字符';}catch(e){document.getElementById('core-ta').value='';document.getElementById('core-len').textContent='加载失败';}}
document.getElementById('core-ta')?.addEventListener('input',function(){document.getElementById('core-len').textContent=this.value.length+' 字符';});
async function saveCore(){const v=document.getElementById('core-ta').value;try{await api('update_system_config',{key:'cross_window_memory',value:v});toast('已保存');}catch(e){toast('保存失败');}}

// Chat Params
const THINK_DESCS={off:'不启用思考模式',auto:'模型自动决定思考深度',light:'快速校验，~1024 tokens，适合日常对话',medium:'多步推理，~16K tokens，适合分析和代码',heavy:'深度推理，~32K tokens，适合复杂逻辑'};
function setThinkSeg(btn){const seg=document.getElementById('cp-think-seg');seg.querySelectorAll('.seg-btn').forEach(b=>b.classList.remove('on'));btn.classList.add('on');document.getElementById('cp-think-desc').textContent=THINK_DESCS[btn.dataset.val]||'';}
function getThinkVal(){const btn=document.querySelector('#cp-think-seg .seg-btn.on');return btn?btn.dataset.val:'off';}
function applyThinkVal(v){const valid=['off','auto','light','medium','heavy'];if(typeof v==='number')v=v===0?'off':v<=1024?'light':v<=16000?'medium':'heavy';if(!valid.includes(v))v='off';const seg=document.getElementById('cp-think-seg');seg.querySelectorAll('.seg-btn').forEach(b=>{b.classList.toggle('on',b.dataset.val===v);});document.getElementById('cp-think-desc').textContent=THINK_DESCS[v]||'';}
async function loadChatParams(){try{const d=await api('get_system_config',{key:'chat_settings'});let s={temperature:1.0,top_p:null,max_tokens:0,context_messages:50,thinking_budget:'off',stream:true};if(d?.value){try{s={...s,...JSON.parse(d.value)};}catch{}}document.getElementById('cp-temp').value=s.temperature;document.getElementById('cp-temp-val').textContent=parseFloat(s.temperature).toFixed(2);const hasTopP=s.top_p!==null&&s.top_p!==undefined&&s.top_p>0;document.getElementById('cp-topp-on').checked=hasTopP;document.getElementById('cp-topp-range').style.display=hasTopP?'block':'none';if(hasTopP){document.getElementById('cp-topp').value=s.top_p;document.getElementById('cp-topp-val').textContent=parseFloat(s.top_p).toFixed(2);}else{document.getElementById('cp-topp-val').textContent='0.90';}document.getElementById('cp-ctx').value=s.context_messages;document.getElementById('cp-ctx-val').textContent=s.context_messages;applyThinkVal(s.thinking_budget);document.getElementById('cp-maxtk').value=s.max_tokens;document.getElementById('cp-stream').checked=s.stream!==false;}catch(e){toast('加载失败');}}
async function saveChatParams(){const s={temperature:parseFloat(document.getElementById('cp-temp').value),top_p:document.getElementById('cp-topp-on').checked?parseFloat(document.getElementById('cp-topp').value):null,max_tokens:parseInt(document.getElementById('cp-maxtk').value)||0,context_messages:parseInt(document.getElementById('cp-ctx').value)||50,thinking_budget:getThinkVal(),stream:document.getElementById('cp-stream').checked};try{await api('update_system_config',{key:'chat_settings',value:JSON.stringify(s)});toast('参数已保存');}catch(e){toast('保存失败');}}

async function loadData(){document.getElementById('d-conv').textContent=S.allC.length+' 个';try{const n=await api('list_notes');document.getElementById('d-note').textContent=(n?.notes?.length||0)+' 条';}catch(e){}document.getElementById('d-mem').textContent='—';}
